### ISSUE TITLE
.stl file are downloading

### ISSUE THREAD

**Issue by drinkwater2018** [UltiBots/MKVS#1]
hi, 
Thanks for uploading your project files.
I am trying to download the .stl files but could not able to download all file, can you please fix this issue.

Thanks
Arun

**Comment by Verohomie** [comment]
I opened a Chrome browser in incognito and navigated to https://github.com/Verohomie/MKVS then FILES>Download ZIP. All files downloaded in a ZIP. When extracted all STLs opened fine in a viewer. Try this link too... https://github.com/Verohomie/MKVS/archive/refs/heads/master.zip
